export default [
    {
        id:1,
        name: "Scotchmans Hill Cornellius Syrah",
        vintage: "2016",
        onsale: true,
        onSalePrice: 0,
        price: 200.25,
        quantity: 1,
        thumbnail: "./assets/W-SA-013-PT-205.JPG",
        scores: {
            am: "90-92",
            ws: "93",
            wa: "91",
        },
        country: "Taiwan",
        region: "Weigo",
        capacity: 1,
        unit: "L",
    },{
        id: 2,
        name: "Scotchmans Hill Cornellius Syrah",
        vintage: "2016",
        onsale: true,
        onSalePrice: 0,
        price: 200.25,
        quantity: 1,
        thumbnail: "./assets/W-SA-013-PT-205.JPG",
        scores: {
            am: "90-92",
            ws: "93",
            wa: "91",
        },
        country: "Taiwan",
        region: "Weigo",
        capacity: 1,
        unit: "L",
    },
    {
        id: 3,
        name: "Hello",
        vintage: "ss",
        onsale: true,
        onSalePrice: 200.25,
        price: 300,
        quantity: 0,
        thumbnail: "./assets/W-SA-013-PT-205.JPG",
        scores: {
            am: "90-92",
            ws: "93",
            wa: "91",
        },
        country: "Taiwan",
        region: "Weigo",
        capacity: 1,
        unit: "L",
    },
    {
        id: 4,
        name: "Scotchmans Hill Cornellius Syrah",
        vintage: "ss",
        onsale: true,
        onSalePrice: 0,
        price: 400,
        quantity: 5,
        thumbnail: "./assets/W-SA-013-PT-205.JPG",
        scores: {
            am: "90-92",
            ws: "93",
            wa: "91",
        },
        country: "Taiwan",
        region: "Weigo",
        capacity: 1,
        unit: "L",
    },
     {
        id:5,
        name: "Scotchmans Hill Cornellius Syrah",
        vintage: "2016",
        onsale: true,
        onSalePrice: 180,
        price: 200.25,
        quantity: 1,
        thumbnail: "./assets/W-SA-013-PT-205.JPG",
        scores: {
            am: "90-92",
            ws: "93",
            wa: "91",
        },
        country: "Taiwan",
        region: "Weigo",
        capacity: 1,
        unit: "L",
    },{
        id: 6,
        name: "Scotchmans Hill Cornellius Syrah",
        vintage: "2016",
        onsale: true,
        onSalePrice: 0,
        price: 200.25,
        quantity: 1,
        thumbnail: "./assets/W-SA-013-PT-205.JPG",
        scores: {
            am: "90-92",
            ws: "93",
            wa: "91",
        },
        country: "Taiwan",
        region: "Weigo",
        capacity: 1,
        unit: "L",
    },
    {
        id: 7,
        name: "Scotchmans Hill Cornellius Syrah",
        vintage: "ss",
        onsale: true,
        onSalePrice: 200.25,
        price: 300,
        quantity: 0,
        thumbnail: "./assets/W-SA-013-PT-205.JPG",
        scores: {
            am: "90-92",
            ws: "93",
            wa: "91",
        },
        country: "Taiwan",
        region: "Weigo",
        capacity: 1,
        unit: "L",
    },
    {
        id: 8,
        name: "Scotchmans Hill Cornellius Syrah",
        vintage: "ss",
        onsale: true,
        onSalePrice: 0,
        price: 400,
        quantity: 5,
        thumbnail: "./assets/W-SA-013-PT-205.JPG",
        scores: {
            am: "90-92",
            ws: "93",
            wa: "91",
        },
        country: "Taiwan",
        region: "Weigo",
        capacity: 1,
        unit: "L",
    },
    {
        id:9,
        name: "Scotchmans Hill Cornellius Syrah",
        vintage: "2016",
        onsale: true,
        onSalePrice: 0,
        price: 200.25,
        quantity: 1,
        thumbnail: "./assets/W-SA-013-PT-205.JPG",
        scores: {
            am: "90-92",
            ws: "93",
            wa: "91",
        },
        country: "Taiwan",
        region: "Weigo",
        capacity: 1,
        unit: "L",
    },{
        id: 10,
        name: "Scotchmans Hill Cornellius Syrah",
        vintage: "2016",
        onsale: true,
        onSalePrice: 0,
        price: 200.25,
        quantity: 1,
        thumbnail: "./assets/W-SA-013-PT-205.JPG",
        scores: {
            am: "90-92",
            ws: "93",
            wa: "91",
        },
        country: "Taiwan",
        region: "Weigo",
        capacity: 1,
        unit: "L",
    },
    {
        id: 11,
        name: "Scotchmans Hill Cornellius Syrah",
        vintage: "ss",
        onsale: true,
        onSalePrice: 200.25,
        price: 300,
        quantity: 0,
        thumbnail: "./assets/W-SA-013-PT-205.JPG",
        scores: {
            am: "90-92",
            ws: "93",
            wa: "91",
        },
        country: "Taiwan",
        region: "Weigo",
        capacity: 1,
        unit: "L",
    },
    {
        id: 12,
        name: "Scotchmans Hill Cornellius Syrah",
        vintage: "ss",
        onsale: true,
        onSalePrice: 0,
        price: 400,
        quantity: 5,
        thumbnail: "./assets/W-SA-013-PT-205.JPG",
        scores: {
            am: "90-92",
            ws: "93",
            wa: "91",
        },
        country: "Taiwan",
        region: "Weigo",
        capacity: 1,
        unit: "L",
    },
];