export default [
    {
        id: 2,
        name: "Scotchmans Hill Cornellius Syrah",
        vintage: "2016",
        onsale: true,
        onSalePrice: 0,
        price: 200.25,
        quantity: 1,
        thumbnail: "./assets/W-SA-013-PT-205.JPG",
        scores: {
            am: "90-92",
            ws: "93",
            wa: "91",
        },
        country: "Taiwan",
        region: "Weigo",
        capacity: 1,
        unit: "L",
    },
    {
        id: 2,
        name: "Hello",
        vintage: "ss",
        onsale: true,
        onSalePrice: 200.25,
        price: 300,
        quantity: 1,
        thumbnail: "",
        scores: {
            am: "90-92",
            ws: "93",
            wa: "91",
        },
        country: "Taiwan",
        region: "Weigo",
        capacity: 1,
        unit: "L",
    },
    {
        id: 3,
        name: "Hello",
        vintage: "ss",
        onsale: true,
        onSalePrice: 0,
        price: 0,
        quantity: 1,
        thumbnail: "",
        scores: {
            am: "90-92",
            ws: "93",
            wa: "91",
        },
        country: "Taiwan",
        region: "Weigo",
        capacity: 1,
        unit: "L",
    },
];